INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:38] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:38] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:38] "GET /_dash-dependencies HTTP/1.1" 200 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:38] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:38] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:38] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:39] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:39] "GET /_dash-dependencies HTTP/1.1" 200 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:39] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:39] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:40] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:41] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:47] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:49] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:50] "GET /_dash-component-suites/dash/deps/react@16.v2_16_1m1714615247.14.0.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:50] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1714615247.14.0.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:50] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_16_1m1714615247.8.1.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:51] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_16_1m1714615247.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:51] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:51] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:51] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x000002A6E5406570>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:03:56] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:04:38] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:05:38] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:38] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:40] "GET /_reload-hash HTTP/1.1" 200 -
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:44] "GET /_reload-hash HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_dash-component-suites/dash/deps/react@16.v2_16_1m1714615247.14.0.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_dash-component-suites/dash/deps/react-dom@16.v2_16_1m1714615247.14.0.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_dash-component-suites/dash/deps/prop-types@15.v2_16_1m1714615247.8.1.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_dash-component-suites/dash/dash-renderer/build/dash_renderer.v2_16_1m1714615247.min.js HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:46] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:50] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:50] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 13, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000193E42F6520>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:06:51] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:08:02] "GET /_dash-component-suites/dash/dcc/dash_core_components-shared.js.map HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:08:02] "GET /_dash-component-suites/dash/dcc/dash_core_components.js.map HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:08:02] "GET /_dash-component-suites/dash/html/dash_html_components.min.js.map HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:08:02] "GET /_dash-component-suites/dash/dash_table/bundle.js.map HTTP/1.1" 200 -
DEBUG:root:Starting Dash app
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "[36mGET /_dash-component-suites/dash/dcc/dash_core_components.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "[36mGET /_dash-component-suites/dash/dcc/dash_core_components-shared.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "[36mGET /_dash-component-suites/dash/html/dash_html_components.min.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "[36mGET /_dash-component-suites/dash/dash_table/bundle.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
DEBUG:root:Entering dispatch method
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:07] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
DEBUG:root:Entering dispatch method
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Entering dispatch method
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:10] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:11] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:11] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Entering dispatch method
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
DEBUG:root:Entering dispatch method
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:11] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
ERROR:dash_dispatch:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\Examples\dash_dispatch", line 14, in dispatch
    if not ctx.triggered:
           ^^^^^^^^^^^^^
  File "D:\DashLayoutHelper\vdash\Lib\site-packages\dash\_callback_context.py", line 19, in assert_context
    if not context_value.get():
           ^^^^^^^^^^^^^^^^^^^
LookupError: <ContextVar name='callback_context' at 0x00000226433C6AC0>
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:10:11] "[35m[1mPOST /_dash-update-component HTTP/1.1[0m" 500 -
DEBUG:root:Starting Dash app
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "[36mGET /_dash-component-suites/dash/dcc/dash_core_components.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "[36mGET /_dash-component-suites/dash/dcc/dash_core_components-shared.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "[36mGET /_dash-component-suites/dash/dash_table/bundle.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "[36mGET /_dash-component-suites/dash/html/dash_html_components.min.js.map HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: initial value
DEBUG:root:Returning value: initial value
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:50] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:11:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Starting Dash app
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:42] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:42] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:42] "GET /_dash-dependencies HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:42] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: initial value
DEBUG:root:Returning value: initial value
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:42] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:43] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:44] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:44] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Error message: 
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:45] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:46] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: 
DEBUG:root:Returning value: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:47] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:47] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: d
DEBUG:root:Returning value: d
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:47] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:47] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: di
DEBUG:root:Returning value: di
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dis
DEBUG:root:Returning value: dis
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: disp
DEBUG:root:Returning value: disp
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dispa
DEBUG:root:Returning value: dispa
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dispal
DEBUG:root:Returning value: dispal
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dispaly
DEBUG:root:Entering update_global_error callback
DEBUG:root:Returning value: dispaly
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dispal
DEBUG:root:Returning value: dispal
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:48] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dispa
DEBUG:root:Returning value: dispa
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: disp
DEBUG:root:Returning value: disp
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
DEBUG:root:Entering update_output callback with value: displ
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Returning value: displ
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: displa
DEBUG:root:Returning value: displa
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: display
DEBUG:root:Returning value: display
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:49] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: 
DEBUG:root:Returning value: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:51] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:51] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:54] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: errore
DEBUG:root:Returning value: errore
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:55] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:55] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: errorer
DEBUG:root:Returning value: errorer
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:56] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: errore
DEBUG:root:Returning value: errore
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:57] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:58] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:13:58] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Starting Dash app
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "GET /_dash-dependencies HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: initial value
DEBUG:root:Returning value: initial value
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:03] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Entering update_global_error callback
DEBUG:root:Returning value: e
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:05] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:05] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
DEBUG:root:Entering update_global_error callback
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:06] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: 
DEBUG:root:Returning value: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:08] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: d
DEBUG:root:Entering update_global_error callback
DEBUG:root:Returning value: d
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:09] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:09] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: da
DEBUG:root:Returning value: da
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:09] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:09] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dad
DEBUG:root:Returning value: dad
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:10] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:10] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dadf
DEBUG:root:Returning value: dadf
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:10] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:10] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: dad
DEBUG:root:Returning value: dad
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: da
DEBUG:root:Returning value: da
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: d
DEBUG:root:Returning value: d
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: 
DEBUG:root:Returning value: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:11] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
DEBUG:root:Entering update_global_error callback
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:12] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:13] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:16:13] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Starting Dash app
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:8050
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:29] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:29] "GET /_favicon.ico?v=2.16.1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:30] "GET /_dash-layout HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:30] "GET /_dash-dependencies HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: initial value
DEBUG:root:Returning value: initial value
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:30] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:30] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:32] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:32] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:33] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:34] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:34] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: 
DEBUG:root:Returning value: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:35] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:36] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:36] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: error
DEBUG:root:Value is "error", raising ValueError
ERROR:root:Caught Exception: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:37] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: erro
DEBUG:root:Returning value: erro
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: err
DEBUG:root:Returning value: err
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: er
DEBUG:root:Returning value: er
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: e
DEBUG:root:Returning value: e
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_output callback with value: 
DEBUG:root:Returning value: 
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: An error occurred!
INFO:werkzeug:127.0.0.1 - - [09/Jun/2024 11:18:38] "POST /_dash-update-component HTTP/1.1" 200 -
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: 
ERROR:root:Caught Exception: input is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: input is broken
ERROR:root:Caught Exception: input is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: input is broken
ERROR:root:Caught Exception: data is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: data is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: data is broken
ERROR:root:Caught Exception: data is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: data is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: data is broken
ERROR:root:Caught Exception: data is broken
DEBUG:root:Entering update_global_error callback
DEBUG:root:Error message: Error: data is broken
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

ERROR:root:Caught Exception: data is broken
ERROR:root:Caught Exception: data is broken
ERROR:root:Caught Exception: data is broken
ERROR:root:Caught Exception: input is broken
ERROR:root:Caught Exception: input is broken
ERROR:root:Caught Exception: input is broken
ERROR:root:Caught Exception: input is broken
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

ERROR:root:Caught Exception: data is broken
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

ERROR:root:Caught Exception: data is broken
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

ERROR:root:Caught Exception: data is broken
INFO:dash.dash:Dash is running on http://127.0.0.1:8050/

